# Generated by Django 5.0 on 2023-12-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_bonus', models.PositiveSmallIntegerField(choices=[(1000, 'от 1000р до 2000р'), (500, 'от 500р до 1000р'), (100, 'от 100р до 500р'), (0, 'Бюджет не ограничен')], verbose_name='Премиальное участие в игре Тайный Санта')),
            ],
        ),
        migrations.CreateModel(
            name='UserSantaGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_game_start', models.BooleanField(blank=True, default=False, null=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='santa_game_partner', to='tg_bot.usersantagame', verbose_name='Ваш партнер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Лист пожеланий')),
            ],
            options={
                'verbose_name': 'Лист желаний',
                'verbose_name_plural': 'Листы желаний',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Описание игры')),
                ('end_game', models.DateTimeField(help_text='Дата окончания игры', verbose_name='Дата окончания игры')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonus', to='tg_bot.bonus')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('usersantagame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tg_bot.usersantagame')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            bases=('tg_bot.usersantagame',),
        ),
        migrations.AddField(
            model_name='usersantagame',
            name='my_wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='tg_bot.wishlist', verbose_name='Пожелание'),
        ),
    ]
