# Generated by Django 5.0 on 2023-12-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='promo_key',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='ПРОМО'),
        ),
    ]
