# Generated by Django 4.2.8 on 2023-12-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0002_game_promo_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersantagame",
            name="my_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game",
                to="tg_bot.game",
                verbose_name="Моя игра",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="end_game",
            field=models.DateField(
                help_text="Дата окончания игры", verbose_name="Дата окончания игры"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="promo_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=6, null=True, verbose_name="ПРОМО"
            ),
        ),
    ]
