# Generated by Django 4.2.8 on 2023-12-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0003_usersantagame_my_game_alter_game_end_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersantagame",
            name="my_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="tg_bot.game",
                verbose_name="Моя игра",
            ),
        ),
    ]
