# Generated by Django 4.2.8 on 2023-12-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0004_alter_usersantagame_my_game"),
    ]

    operations = [
        migrations.RenameModel(old_name="SuperUser", new_name="Assistant",),
        migrations.AlterField(
            model_name="usersantagame",
            name="is_game_start",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Создатель игры"
            ),
        ),
        migrations.AlterField(
            model_name="usersantagame",
            name="my_wish",
            field=models.TextField(blank=True, null=True, verbose_name="Пожелание"),
        ),
        migrations.AlterField(
            model_name="usersantagame",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="tg_bot.usersantagame",
                verbose_name="Ваш партнер",
            ),
        ),
        migrations.DeleteModel(name="WishList",),
    ]
