# Generated by Django 4.2.8 on 2023-12-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0005_rename_superuser_assistant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="bonus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="tg_bot.bonus",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="end_game",
            field=models.DateField(
                blank=True,
                help_text="Дата окончания игры",
                null=True,
                verbose_name="Дата окончания игры",
            ),
        ),
    ]
